[workspace]
resolver = "2"
members = [
    "crates/domain",
    "crates/app",
    "crates/adapter-store",
    "crates/adapter-docker",
    "crates/tools/parser",
    "crates/tools/wrappers/arjun",
    "crates/tools/wrappers/commix",
    "crates/tools/wrappers/feroxbuster",
    "crates/tools/wrappers/ffuf",
    "crates/tools/wrappers/gobuster",
    "crates/tools/wrappers/httpx",
    "crates/tools/wrappers/katana",
    "crates/tools/wrappers/nikto",
    "crates/tools/wrappers/nmap",
    "crates/tools/wrappers/nuclei",
    "crates/tools/wrappers/sqlmap",
    "crates/tools/wrappers/wafw00f",
    "crates/tools/wrappers/whatweb",
    "crates/tools/registry",
    "crates/cli",
    "crates/xtask",
]

[workspace.package]
version = "0.0.1" # x-release-please-version
edition = "2021"
license = "MIT"
