[workspace]
resolver = "2"
members = [
    "crates/domain",
    "crates/app",
    "crates/adapter-store",
    "crates/adapter-docker",
    "crates/tools/parser",
    "crates/tools/wrappers/arjun",
    "crates/tools/wrappers/authz",
    "crates/tools/wrappers/bandit",
    "crates/tools/wrappers/brakeman",
    "crates/tools/wrappers/browser",
    "crates/tools/wrappers/checkov",
    "crates/tools/wrappers/commix",
    "crates/tools/wrappers/corsy",
    "crates/tools/wrappers/crack",
    "crates/tools/wrappers/crlfuzz",
    "crates/tools/wrappers/dalfox",
    "crates/tools/wrappers/dnsx",
    "crates/tools/wrappers/dotdotpwn",
    "crates/tools/wrappers/feroxbuster",
    "crates/tools/wrappers/fetch",
    "crates/tools/wrappers/ffuf",
    "crates/tools/wrappers/fuxploider",
    "crates/tools/wrappers/gau",
    "crates/tools/wrappers/ghauri",
    "crates/tools/wrappers/git-dumper",
    "crates/tools/wrappers/gitleaks",
    "crates/tools/wrappers/gobuster",
    "crates/tools/wrappers/gosec",
    "crates/tools/wrappers/gospider",
    "crates/tools/wrappers/gowitness",
    "crates/tools/wrappers/grype",
    "crates/tools/wrappers/hadolint",
    "crates/tools/wrappers/hydra",
    "crates/tools/wrappers/httpx",
    "crates/tools/wrappers/jwt",
    "crates/tools/wrappers/katana",
    "crates/tools/wrappers/nikto",
    "crates/tools/wrappers/njsscan",
    "crates/tools/wrappers/nmap",
    "crates/tools/wrappers/nuclei",
    "crates/tools/wrappers/osv-scanner",
    "crates/tools/wrappers/semgrep",
    "crates/tools/wrappers/sqlmap",
    "crates/tools/wrappers/sstimap",
    "crates/tools/wrappers/subfinder",
    "crates/tools/wrappers/tlsx",
    "crates/tools/wrappers/trivy",
    "crates/tools/wrappers/trufflehog",
    "crates/tools/wrappers/wafw00f",
    "crates/tools/wrappers/whatweb",
    "crates/tools/registry",
    "crates/cli",
    "crates/xtask",
]

[workspace.package]
version = "0.0.1" # x-release-please-version
edition = "2021"
license = "MIT"
