use std::collections::BTreeMap;
use std::process::Command;

fn main() {
    let mut args = std::env::args().skip(1);
    let sub = args.next().unwrap_or_default();
    if sub != "attack-sync" {
        eprintln!("usage: xtask attack-sync [--version <v>] [--input <path>] [--out <path>]");
        std::process::exit(2);
    }

    let mut version = String::from("19.2");
    let mut input: Option<String> = None;
    let mut out = String::from("crates/domain/src/attack/generated.rs");
    while let Some(a) = args.next() {
        match a.as_str() {
            "--version" => version = args.next().expect("--version needs a value"),
            "--input" => input = Some(args.next().expect("--input needs a value")),
            "--out" => out = args.next().expect("--out needs a value"),
            other => {
                eprintln!("unknown argument: {other}");
                std::process::exit(2);
            }
        }
    }

    let bytes = match &input {
        Some(path) => std::fs::read(path).expect("read --input file"),
        None => download(&version),
    };
    let bundle: serde_json::Value = serde_json::from_slice(&bytes).expect("parse STIX bundle");
    let objects = bundle["objects"]
        .as_array()
        .expect("bundle has objects array");

    let mut shortname_to_ta: BTreeMap<String, String> = BTreeMap::new();
    let mut tactics: BTreeMap<String, String> = BTreeMap::new();
    for o in objects {
        if o["type"] != "x-mitre-tactic" || is_gone(o) {
            continue;
        }
        let Some(ta) = external_id(o) else { continue };
        let name = o["name"].as_str().unwrap_or_default().to_string();
        let shortname = o["x_mitre_shortname"]
            .as_str()
            .unwrap_or_default()
            .to_string();
        shortname_to_ta.insert(shortname, ta.clone());
        tactics.insert(ta, name);
    }

    let mut techniques: BTreeMap<String, (String, Vec<String>, Option<String>)> = BTreeMap::new();
    for o in objects {
        if o["type"] != "attack-pattern" || is_gone(o) {
            continue;
        }
        let Some(id) = external_id(o) else { continue };
        let name = o["name"].as_str().unwrap_or_default().to_string();
        let mut tas: Vec<String> = Vec::new();
        if let Some(phases) = o["kill_chain_phases"].as_array() {
            for p in phases {
                if p["kill_chain_name"] != "mitre-attack" {
                    continue;
                }
                let Some(shortname) = p["phase_name"].as_str() else {
                    continue;
                };
                if let Some(ta) = shortname_to_ta.get(shortname) {
                    tas.push(ta.clone());
                }
            }
        }
        tas.sort();
        tas.dedup();
        let parent = id.split_once('.').map(|(base, _)| base.to_string());
        techniques.insert(id, (name, tas, parent));
    }

    let mut s = String::new();
    s.push_str(&format!(
        "//! @generated by `cargo xtask attack-sync` from MITRE ATT&CK Enterprise v{version}. Do not edit.\n\n"
    ));
    s.push_str("use super::{AttackTactic, AttackTechnique};\n\n");
    s.push_str("pub(super) static TACTICS: &[AttackTactic] = &[\n");
    for (id, name) in &tactics {
        s.push_str(&format!(
            "    AttackTactic {{ id: {}, name: {} }},\n",
            lit(id),
            lit(name)
        ));
    }
    s.push_str("];\n\n");
    s.push_str("pub(super) static TECHNIQUES: &[AttackTechnique] = &[\n");
    for (id, (name, tas, parent)) in &techniques {
        let tactics_lit: Vec<String> = tas.iter().map(|t| lit(t)).collect();
        let parent_lit = match parent {
            Some(p) => format!("Some({})", lit(p)),
            None => String::from("None"),
        };
        s.push_str(&format!(
            "    AttackTechnique {{ id: {}, name: {}, tactics: &[{}], parent: {} }},\n",
            lit(id),
            lit(name),
            tactics_lit.join(", "),
            parent_lit
        ));
    }
    s.push_str("];\n");

    std::fs::write(&out, s).expect("write generated matrix");
    eprintln!(
        "wrote {} tactics and {} techniques to {out}",
        tactics.len(),
        techniques.len()
    );
}

fn is_gone(o: &serde_json::Value) -> bool {
    o["revoked"].as_bool().unwrap_or(false) || o["x_mitre_deprecated"].as_bool().unwrap_or(false)
}

fn external_id(o: &serde_json::Value) -> Option<String> {
    o["external_references"].as_array()?.iter().find_map(|r| {
        if r["source_name"] == "mitre-attack" {
            r["external_id"].as_str().map(str::to_string)
        } else {
            None
        }
    })
}

fn lit(s: &str) -> String {
    serde_json::to_string(s).expect("encode string literal")
}

fn download(version: &str) -> Vec<u8> {
    let url = format!(
        "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/enterprise-attack/enterprise-attack-{version}.json"
    );
    let out = Command::new("curl")
        .args(["-sSL", &url])
        .output()
        .expect("run curl to download the ATT&CK STIX bundle");
    if !out.status.success() {
        panic!("curl failed: {}", String::from_utf8_lossy(&out.stderr));
    }
    out.stdout
}
