[package]
name = "searu-tool-registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
searu-domain = { path = "../../domain" }
searu-tool-arjun = { path = "../wrappers/arjun" }
searu-tool-bandit = { path = "../wrappers/bandit" }
searu-tool-commix = { path = "../wrappers/commix" }
searu-tool-dalfox = { path = "../wrappers/dalfox" }
searu-tool-feroxbuster = { path = "../wrappers/feroxbuster" }
searu-tool-ffuf = { path = "../wrappers/ffuf" }
searu-tool-ghauri = { path = "../wrappers/ghauri" }
searu-tool-gitleaks = { path = "../wrappers/gitleaks" }
searu-tool-gobuster = { path = "../wrappers/gobuster" }
searu-tool-gosec = { path = "../wrappers/gosec" }
searu-tool-httpx = { path = "../wrappers/httpx" }
searu-tool-katana = { path = "../wrappers/katana" }
searu-tool-nikto = { path = "../wrappers/nikto" }
searu-tool-nmap = { path = "../wrappers/nmap" }
searu-tool-nuclei = { path = "../wrappers/nuclei" }
searu-tool-semgrep = { path = "../wrappers/semgrep" }
searu-tool-sqlmap = { path = "../wrappers/sqlmap" }
searu-tool-trufflehog = { path = "../wrappers/trufflehog" }
searu-tool-wafw00f = { path = "../wrappers/wafw00f" }
searu-tool-whatweb = { path = "../wrappers/whatweb" }
