[package]
name = "searu-tool-registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
searu-domain = { path = "../../domain" }
searu-tool-arjun = { path = "../wrappers/arjun" }
searu-tool-bandit = { path = "../wrappers/bandit" }
searu-tool-brakeman = { path = "../wrappers/brakeman" }
searu-tool-checkov = { path = "../wrappers/checkov" }
searu-tool-commix = { path = "../wrappers/commix" }
searu-tool-corsy = { path = "../wrappers/corsy" }
searu-tool-crlfuzz = { path = "../wrappers/crlfuzz" }
searu-tool-dalfox = { path = "../wrappers/dalfox" }
searu-tool-dnsx = { path = "../wrappers/dnsx" }
searu-tool-dotdotpwn = { path = "../wrappers/dotdotpwn" }
searu-tool-feroxbuster = { path = "../wrappers/feroxbuster" }
searu-tool-ffuf = { path = "../wrappers/ffuf" }
searu-tool-gau = { path = "../wrappers/gau" }
searu-tool-ghauri = { path = "../wrappers/ghauri" }
searu-tool-gitleaks = { path = "../wrappers/gitleaks" }
searu-tool-gobuster = { path = "../wrappers/gobuster" }
searu-tool-gosec = { path = "../wrappers/gosec" }
searu-tool-gospider = { path = "../wrappers/gospider" }
searu-tool-grype = { path = "../wrappers/grype" }
searu-tool-hadolint = { path = "../wrappers/hadolint" }
searu-tool-httpx = { path = "../wrappers/httpx" }
searu-tool-katana = { path = "../wrappers/katana" }
searu-tool-nikto = { path = "../wrappers/nikto" }
searu-tool-njsscan = { path = "../wrappers/njsscan" }
searu-tool-nmap = { path = "../wrappers/nmap" }
searu-tool-nuclei = { path = "../wrappers/nuclei" }
searu-tool-osv-scanner = { path = "../wrappers/osv-scanner" }
searu-tool-semgrep = { path = "../wrappers/semgrep" }
searu-tool-sqlmap = { path = "../wrappers/sqlmap" }
searu-tool-subfinder = { path = "../wrappers/subfinder" }
searu-tool-tlsx = { path = "../wrappers/tlsx" }
searu-tool-trivy = { path = "../wrappers/trivy" }
searu-tool-trufflehog = { path = "../wrappers/trufflehog" }
searu-tool-wafw00f = { path = "../wrappers/wafw00f" }
searu-tool-whatweb = { path = "../wrappers/whatweb" }
