[package]
name = "searu"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "searu"
path = "src/main.rs"

[dependencies]
clap = "4.6.6"
searu-domain = { path = "../domain" }
searu-app = { path = "../app" }
searu-adapter-store = { path = "../adapter-store" }
searu-adapter-docker = { path = "../adapter-docker" }
searu-tool-registry = { path = "../tools/registry" }
serde_json = "1.0.151"

[dev-dependencies]
assert_cmd = "2.2.2"
predicates = "3.1.4"
tempfile = "3.27.0"
